import { readFile } from 'fs/promises';
import { WasmInterpreter } from '../pkg/spartan_vm_wasm.js';

async function main() {
    console.log('Loading Spartan VM WASM module...');

    // Create interpreter instance
    const interpreter = new WasmInterpreter();

    // Load bytecode and layouts from the compiled example
    // These files are generated by running: cargo run --release -- --root noir_examples/many_poseidons
    const bytecodeDir = '../../noir_examples/many_poseidons/spartan_vm_debug';

    try {
        console.log('Loading witgen bytecode...');
        const witgenBytecode = await readFile(`${bytecodeDir}/witgen.bin`);
        interpreter.load_witgen_bytecode(witgenBytecode);

        console.log('Loading layouts...');
        const layoutsJson = await readFile(`${bytecodeDir}/layouts.json`, 'utf-8');
        interpreter.load_layouts(layoutsJson);

        // For many_poseidons, the inputs from Prover.toml are: input="2", out="..."
        console.log('Preparing inputs...');
        const inputs = [
            "2",
            "17988182159117295307234504899192092167905999116349671907177110574981469137649"
        ];

        console.log('Executing witgen with branching interpreter...');
        const result = await interpreter.execute_witgen(JSON.stringify(inputs));

        console.log('\nExecution completed!');
        console.log('Witness pre-commitment size:', result.witness_pre_comm.length);
        console.log('Witness post-commitment size:', result.witness_post_comm.length);
        console.log('A vector size:', result.a.length);
        console.log('B vector size:', result.b.length);
        console.log('C vector size:', result.c.length);

        console.log('\nFirst few witness values:');
        console.log(result.witness_pre_comm.slice(0, 5));

        console.log('\n✓ WASM interpreter test passed!');
    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
}

main();
